### ISSUE TITLE
Small request: Add Golem topic to repository

### ISSUE THREAD

**Issue by cryptobench** [anshuman73/DeML-Golem#1]
Hello!

It would be much appreciated if you could add the topic **golem** to the repository!
That would mean people could find all the awesome projects by just exploring the topic **golem** here https://github.com/topics/golem, and hopefully create a little bit more exposure for this awesome project! :heart:

There will be a settings wheel on the right side of the screenshot if you head over to your repository's main page, click that and you should see the option to add a topic.
![image](https://user-images.githubusercontent.com/33448819/104737054-0fd5e200-5744-11eb-9249-517e1ceffc8d.png)

**Comment by anshuman73** [comment]
Hi Phillip!

Done! Sorry for the delay. I was AFK for a bit!

**Comment by cryptobench** [comment]
Hi!

No worries bud, it was just a minor request. Thanks for taking your time to add the topic! :heart: 👍
